export default {
    chainswap: {
        name: 'ChainSwap',
        Token: 'TOKEN',
        Time1: 'Apr.19th 21:00',
        Time2: 'Apr.23rd 21:00',
        Time3: 'Apr.24th 21:00',
        Time1UTC: '2021/04/19 21:00 UTC+8',
        Time2UTC: '2021/04/23 21:00 UTC+8',
        Time3UTC: '2021/04/24 21:00 UTC+8',
        Collateral: '0x3b73c1b2ea59835cbfcadade5462b6ab630d9890',
        Underlying: '0xe9e7cea3dedca5984780bafc599bd69add087d56',
        LongAdress: '0x029A09ABE791a3Be60Aa64d569F4C34890f24097',
        ActivePrice: 0.3,
        ProjcetInformation: {
            ProjectName: 'ChainSwap',
            Distributing: 'Apr. 19th 21:00 SGT',
            Activating: 'Apr. 23rd 21:00 SGT',
            ActivatePeriod: '24hours',
            ActivatingxPrice: '1TOKEN=0.3BUSD',
            TicketPrice: '1 Helmet',
        },
        TokenInformation: {
            TokenName: 'TOKEN',
            Address: '0x3b73c1b2ea59835cbfcadade5462b6ab630d9890',
            Supply: '100,000',
            TotalSupply: '100,000,000',
        },
        About: [
            'ChainSwap is a cross-chain asset bridge & application hub for smart chains. ChainSwap allows projects to seamlessly bridge between ETH, BSC and HECO. In the future ChainSwap will be integrating chains and provide full cross-chain solutions between BTC, DOT, SOL and more.',
            'ChainSwap has closed a $3M strategic funding round with participation from Alameda Research, OK Block Dream Fund (OKEx), NGC Ventures, Spark Digital Capital, Metaconstant Ventures, CMS Holdings, Rarestone Captial, Monday Capital, Continue Capital, SRC Capital, DAO Ventures, Mask network, Particle and Power Law Capital.',
        ],
        TokenDistribution: [
            '$TOKEN is the token of the ChainSwap platform. The total amount is 100M, 2% of the total amount is 100% unlock token, and will be distributed to public sale and airdrop. Public sale will be held as IDO on 5 different platforms with a total amount of 1M. Airdrop that is given to users is also 1M.',
        ],
        Media: {
            Website: {
                type: 'Website',
                link: 'https://www.chainswap.com',
                show: 'www.chainswap.com',
            },
            Twitter: {
                type: 'Twitter',
                link: 'https://twitter.com/chain_swap',
                show: 'https://twitter.com/chain_swap',
            },
            Telegram: {
                type: 'Telegram (EN)',
                link: 'https://t.me/chainswap',
                show: 'https://t.me/chainswap',
            },
            Medium: {
                type: 'Medium',
                link: 'https://chain-swap.medium.com/',
                show: 'https://chain-swap.medium.com/',
            },
        },
    },
    blackhole: {
        name: 'BlackHole',
        Token: 'BLACK',
        Time1: 'Apr.26th 20:00',
        Time2: 'Apr.29th 21:00',
        Time3: 'Apr.30th 21:00',
        Time1UTC: '2021/04/26 20:00 UTC+8',
        Time2UTC: '2021/04/29 21:00 UTC+8',
        Time3UTC: '2021/04/30 21:00 UTC+8',
        Collateral: '0xd714d91A169127e11D8FAb3665d72E8b7ef9Dbe2',
        Underlying: '0xe9e7cea3dedca5984780bafc599bd69add087d56',
        LongAdress: '--',
        ActivePrice: 0.05,
        ProjcetInformation: {
            ProjectName: 'BlackHole Protocol',
            Distributing: 'Apr. 26th 20:00 SGT',
            Activating: 'Apr.  29th 21:00 SGT',
            ActivatePeriod: '24hours',
            ActivatingxPrice: '1BLACK=0.05BUSD',
            TicketPrice: '1 Helmet',
        },
        TokenInformation: {
            TokenName: 'BLACK',
            Address: '0xd714d91A169127e11D8FAb3665d72E8b7ef9Dbe2',
            Supply: '200,000',
            TotalSupply: '100,000,000',
        },
        About: [
            'BlackHole Protocol is an approval-free cross-chain burning platform based on Ethereum network. Any user or project governor could create a burning pool by holding BLACK and old Token LP to permanently burn the old Token into a new Token, thus gaining ecological vitality.',
            'BlackHole Protocol originates from Ethereum network and gradually spread to Polkadot, BSC, Heco, SOL and eventually the whole blockchain world. And BLACK Token will inflation suddenly at the very begining and flashly enter the deflationary model and keep deflating with the process of ecological reconfiguration.',
        ],
        TokenDistribution: [
            'Farming 50%',
            'Eco Fund 10%',
            'Development Team Fund 10%',
            'Marketing 5%',
            'Initial Liquidity 5%',
            'Seed round 5%',
            'Ambassador round 10%',
            'IDO R1  1%',
            'IDO R2  1%',
            'LBP   3%',
        ],
        Media: {
            Website: {
                type: 'Website',
                link: 'https://blackhole.black',
                show: 'https://blackhole.black',
            },
            Twitter: {
                type: 'Twitter',
                link: 'https://twitter.com/blackholeburn?s=11',
                show: 'https://twitter.com/blackholeburn?s=11',
            },
            Telegram: {
                type: 'Telegram (EN)',
                link: 'https://t.me/BlackholeProtocolOfficial',
                show: 'https://t.me/BlackholeProtocolOfficial',
            },
            Medium: {
                type: 'Medium',
                link: 'https://blackholeprotocol.medium.com/',
                show: 'https://blackholeprotocol.medium.com/',
            },
        },
    },
};
