export default {
    hTPT: [
        'hTPT is the call option of TPT.',
        'Total Supply: 5,000,000 (20% for TPT-BUSD LP on Pancakeswap, 40% for FLASH Mining, 40% for Burning BOX) Reasonable strike price: 1 TPT= 0.06BUSD',
        'Expire date: May 3th 24:00 SGT',
        'Example: If you get 1 hTPT, you could swap 0.06 BUSD to 1 TPT by click the ‘activate’ button on TradingView Tab. To be specific, if TPT hit $0.07, you could get $0.01 NET profit by this clicking ‘Activate’ behavior.',
        'If hTPT get expired, it could be a souvenir token',
        'Please do not trade heavily on hTPT.',
    ],
    hDODO: [
        'hDODO is the call option of DODO.',
        'Total Supply: 75,000 (22,000 for vDODO holders, 40,000 for FLASH Mining, 10,000 for Burning BOX) Reasonable strike price: 1 DODO= 10 HELMET',
        'Expire date: Apr. 14th 24:00 SGT',
        "Example: If you get 1 hDODO, you could swap 10 HELMET to 1 DODO by click the 'activate' button on TradingView Tab. To be specific, if DODO hit $21 and HELMET hit $2, you could get $1 profit by this 'Activate' behavior.",
        'If hDODO get expired, it could be souvenir token',
        'Please do not trade heavily on hDODO.',
    ],
    hMATH: [
        'MATH cover miss out policy. (It performs more like a call option of MATH)',
        'In this policy, the ratio of MATH & BNB is 1MATH = 0.014BNB',
        'It is the reasonable activate price, meaning that you could swap 0.014BNB+1$hMATH to 1MATH before the expire date.',
        'For example, if $MATH hit 0.015BNB, you could activate the policy and swap 0.014BNB + 1$hMATH to 1 $MATH on www.helmet.insure, and get 0.001BNB as profit.',
        'Do not trade heavily on $hMATH unless you are clear about the trading risk',
        'As policy holding certification, there is an expiration date for the $hMATH, but as token, it is alive forever.',
    ],
    hAUTO: [
        'AUTO cover miss out policy. (It performs more like a call option of AUTO)',
        'The reasonable activate price is 1AUTO=42BNB, meaning that you could swap 42BNB+1$hAUTO to 1AUTO before the expire date.',
        'For example, if $AUTO hit 50BNB, you could activate the policy and swap 42BNB + 1$hAUTO to 1 $AUTO on www.helmet.insure, and get 8BNB as profit.',
        '$hAUTO Flash Mining',
        'Start: Feb. 23rd 20:00 SGT',
        'End: Mar.9th 24:00',
        'Policy Expire date: Mar. 24th 24:00 SGT',
    ],
    BNB500: [
        '$BNB500 is BNB cover miss out policy.',
        'Limited edition: 1500 ( 500 for Airdrop to LP Miners on helmet.insure and 1000 for Flash Mining)',
        'In this policy, we set a ratio: ',
        'BNB : BUSD = 1:500 ',
        'it means that you could swap 500 BUSD+1$BNB500 to 1BNB. It is the reasonable active price, for example, if BNB hit $600, you could active the policy and swap 500 BUSD + 1 $BNB500 to 1 BNB with 100BUSD profit.',
        'Flash Mining Type: ',
        '$hCTK-$Helmet LP Mining Pool Notice: $hCTK will be expired on 20th Feb. 0:00 SGT , you could activate it ASAP or take part in $BNB500 Flash Mining.',
        'Flash Mining Start: 18th Feb. 24:00 SGT',
        'Flash Mining End: 28th Feb. 24:00 SGT',
        'Expire date: 20th Mar. 24:00 SGT',
    ],
    hCTK: [
        '$CTK cover miss out policy.',
        'In this policy, we set a ratio of Helmet& CTK. HELMET : CTK = 2.5:1 (Anchored $1)',
        'it means that you could swap 2.5Helmet+1$hCTK to 1CTK. It is the reasonable active price, for example, if $CTK hit $1.2, you could active the policy and swap 2.5 $helmet + 1$hCTK to 1 $CTK on www.helmet.insure)',
        'You could activate you policy after all airdrop landing. Since we have more than 9500 addresses to airdrop, it gonna take some time for them to land into your wallet.',
        'Do not trade heavily on LONG & HCCT & hCTK unless you get clear cognition of the trading risk',
        'As policy holding certification, there is an expiration date for the activation, but as token, LONG & HCCT & hCTK is alive forever.',
    ],
    HCCT: [
        'HCCT is the abbreviation of Helmet Cover Cake TokenLiterally, it is the CAKE Cover Miss Out policy ( it is more like the call option of CAKE )',
        'Underlying asset: Cake',
        'Denominated asset: Helmet (it means that if you activate this policy, you would swap 10Helmet for 1Cake with HCCT)',
        'Premium：1Helmet（ from Helmet Vault）',
        'Insurance Price：1CAKE=10Helmet (it means that if you activate this policy, you would swap 10Helmet for 1Cake with 1HCCT)',
        'Supply: 300,000 (80% minted by mining, 20% as initial liquidity)',
        'Reference Activate Price: When “Cake:Helmet ＞1:10”, you could activate this policy ( plz recheck the price to make sure this activation is profitable)',
        'Insurance Period：2021, Feb.15',
        'More details in our Medium.',
    ],
    hFOR: [
        'It is $FOR cover miss out insurance policy (like the call option of $FOR). The reasonable activate price: 1 $FOR=0.25 HELMET.',
        'For example, if $FOR hit 0.3 HELMET, you could swap only 0.25HELMET+1$hFOR to 1 $FOR, and get 0.05HELMET profit.',
        'COMBO Mining period: 15days, from Mar.4th 24:00 SGT to Mar.19th 24:00 SGT (snapshot and Airdrop will be finished before Mar.4th 24:00 SGT)',
        'Expire date: April 4th, 2021',
        'if $hFOR expired, it could be a souvenir token',
        '$hFOR is totally from Airdrop, please do not trade heavily on $hFOR',
    ],
    hBURGER: [
        'A total of $450,000 $hBurger was given away to LPT Miners on helmet.insure (including Helmet-BNB, Helmet-LONG, Helmet-HCCT LPT Pool, PancakeSwap Helmet-BNB Farm) ',
        'Groundbreaking design of Policy Mining for Real Token!!! $60,000 COMBO Mining Bonus of $Helmet & $Burger !',
        'It is $Burger cover miss out policy. The reasonable activate price: 1 $Burger=0.07 BNB. For example, if $Burger hit 0.08 BNB, you could swap 0.07BNB+1$hBurger to 1 $Burger, and get 0.01BNB profit.',
        'Expire date: March, 9th, 2021',
        'More details in our Medium.',
    ],
    QFEI: [
        'It is the call option of $QSD',
        'The ratio of $QSD & $FEI = 1:1',
        'With 1 $QFEI, you could swap 1 $FEI to 1$QSD on the Insurance- Policy you hold Tab before expire date.',
        'Expire date: May 10th',
        'You could farm $KUN by $QFEI-$QSD LPT',
        'Please do not trade heavily on $QFEI.',
    ],
    BHELMET: [
        'Total Supply: 190,000',
        'Activate price: 1HELMET=1.5BUSD, meaning that you could get 1 $HELMET by just $1.5',
        'Expire date: June 16th 00:00 SGT ',
        '$BHELMET is the reward for HELMET-BNB MLP, allowing Helmeters to get Helmet at lower price. ',
        `Remember to activate $bHELMET on 'Policy You Hold' tab and do not trade heavily on $BHELMET.`,
    ],
    iTOKEN: [
        'iToken is the certificate to swap/activate for TOKEN.',
        'Only users who hold iToken could get TOKEN during April 23rd 21:00 SGT - April 24th 21:00 SGT',
        'iToken cannot be activated before/after that time period',
        'iTOKEN activate/swap formula: 1 iTOKEN+0.3BUSD = 1TOKEN',
        'The lifetime of iToken is from Apr. 23rd 21:00 SGT - Apr. 24th 21:00 SGT. ',
        'Please be sure to activate the iToken within the validity period.',
    ],
    QHELMET: [
        '$QHELMET is the policy that allow users to buy HELMET at almost $1.5 ',
        'Total Supply: 60,000',
        'Activate price: 1HELMET=1.5QSD, meaning that you could get 1 $HELMET by just 1.5QSD',
        'Expire date: June 19th 24:00 SGT',
        '$QHELMET is the reward for HELMET-KUN DLP, allowing users to get Helmet at lower price.',
        "Remember to activate $QHELMET on 'Policy You Hold' tab and do not trade heavily on $QHELMET.",
    ],
    hxBURGER: [
        "It is $xBurger's cover miss out policy ( CALL Option of $xBurger). The reasonable activate price: 1 $xBurger=0.1 BNB.",
        'For example, if $xBurger hit 0.2 BNB, you could swap 0.1BNB+1 $hxBurger to 1 $xBurger, and get net 0.1BNB profit.',
        'Total supply: 20,000',
        'Expire date: May, 21st, 2021',
        'Helmet team took 20,000 Helmet as premium for supporting $hxBurger policy creating.',
        'Do not trade heavily on $hxBurger, since if xBurger fail to hit 0.1BNB, $hxBurger would just be a souvenir token.',
    ],
    iBLACK: [
        'iBLACK is the certificate to swap/activate for BLACK. ',
        'Only users who hold iBLACK could get BLACK during April 29th 21:00 SGT — April 30th 21:00 SGT(️iBLACK cannot be activated before/after that time period))',
        'iBLACK activate/swap formula: 1iBLACK+0.05BUSD = 1BLACK',
        'The lifetime of iBLACK is from Apr. 29th 21:00 SGT — Apr. 30th 21:00 SGT. ',
        'Please be sure to activate the iBLACK within the validity period.',
    ],
    iWAR: [
        'iWAR is the certificate to swap/activate for WAR.',
        'Only users who hold iWAR could get WAR during Apr. 30th 21:00 SGT — May 1st 21:00 SGT(iWAR cannot be activated before/after that time period)',
        'iWAR activate/swap formula: 1 iWAR+0.25BUSD  1 WAR',
        'The lifetime of iWAR is from Apr. 30th 21:00 SGT — May 1st 21:00 SGT. ',
        'Please be sure to activate the iWAR within the validity period.',
    ],
    iLEV: [
        'iLEV is the certificate to swap/activate for LEV.',
        'Only users who hold iLEV could get LEV during May 7th 20:00 SGT — May 8th 20:00 SGT (iLEV cannot be activated before/after that time period)',
        'iLEV activate/swap formula: 1 iLEV+0.5BUSD  1 LEV',
        'The lifetime of iLEV is from May 7th 20:00 SGT — May 8th 20:00 SGT. ',
        'Please be sure to activate the iLEV within the validity period.',
    ],
    iWMASS: [
        'IIO WMASS Supply: $50,000 worth of WMASS',
        'iWMASS activate/swap formula: 1 iWMASS+0.35BUSD Swap 1 WMASS',
        'iWMASS Distribution: May 20th 21:00 SGT — May 22nd 21:00 SGT',
        'Activate/swap iWMASS period: May 22nd 21:00 SGT — May 23rd 21:00 SGT.',
    ],
    iCOW: [
        'iCOW is the certificate to swap/activate for COW.',
        'Only users who hold iCOW could get COW during May 25th 22:00 SGT — May 26th 22:00 SGT.(iCOW cannot be activated before/after that time period)',
        'iCOW activate/swap formula: 1 iCOW+0.5BUSD  1 COW',
        'The lifetime of iCOW is from May 25th 22:00 SGT — May 26th 22:00 SGT. ',
        'Please be sure to activate iCOW within the ruled period.',
    ],
    iCTT: [
        'iCTT is the certificate to swap/activate for CTT. ',
        'Only users who hold iCTT could get CTT during May 25th 21:00 SGT — May 26th 21:00 SGT.(iCTT cannot be activated before/after that time period)',
        'iCTT activate/swap formula: 1 iCTT+30BUSD 1 CTT',
        'The lifetime of iCTT is from May 25th 21:00 SGT — May 26th 21:00 SGT. ',
        'Please be sure to activate the iCTT within the validity period.',
    ],
    iPAUL: [
        'IIO PAUL Supply: 100,000,000',
        'iPAUL activate/swap formula: 1 iPAUL+0.002 BUSD Swap 1 PAUL',
        'iPAUL Distribution: May 30th 21:00 SGT - June 1st 21:00 SGT',
        'Activate/swap iPAUL period: June 2nd 21:00 SGT - June 3rd 21:00 SGT',
        'IIO Ticket: 1 $HELMET',
    ],
    hWINGS: [
        'It is $WINGS cover miss out policy ( CALL Option of $WINGS).',
        'The reasonable activate price: 1 $WINGS=9 BUSD.',
        'For example, if $WINGS hit 10 BUSD, you could swap 9BUSD+1 $hWINGS to 1 $WINGS, and get net 1 BUSD profit.',
        'Total supply: 7500',
        'Expire date: July, 10th, 2021',
        ' Do not trade heavily on $hWINGS, b/c if $WINGS fail to hit 9BUSD, $hWING would just be used as short-term mining shovel and a souvenir token.',
    ],
    iXMS: [
        'iXMS is the certificate to swap/activate for XMS. ',
        'Only users who hold iXMS could get XMS during June 14th 18:00 SGT — June 15th 18:00 SGT.(iXMS cannot be activated before/after that time period)',
        'iXMS activate/swap formula: 1 IXMS+0.0828BUSD 1 XMS',
        'The lifetime of iXMS is from May 14th 18:00 SGT — May 15TH 18:00 SGT. ',
        'Please be sure to activate the iXMS within the validity period.',
    ],
};
